/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/credit-applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar solicitudes de crédito
         * @description Lista las solicitudes del partner autenticado, de la más reciente a la más antigua, con paginación por cursor.
         */
        get: operations["listCreditApplications"];
        put?: never;
        /**
         * Crear solicitud de crédito
         * @description Registra la solicitud y dispara la evaluación de fraude y el scoring de forma asíncrona.
         *     Es idempotente por `Idempotency-Key`.
         */
        post: operations["createCreditApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credit-applications/{applicationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identificador de la solicitud de crédito.
                 * @example 7f3b6c1e-2a4d-4e8b-9c0f-1d2e3f4a5b6c
                 */
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        /**
         * Obtener una solicitud de crédito
         * @description Devuelve el estado actual de la solicitud.
         */
        get: operations["getCreditApplication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credit-applications/{applicationId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identificador de la solicitud de crédito.
                 * @example 7f3b6c1e-2a4d-4e8b-9c0f-1d2e3f4a5b6c
                 */
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        /**
         * Obtener la decisión de una solicitud
         * @description Devuelve el puntaje, la decisión y los códigos de razón que la explican.
         *     Responde `404` mientras la solicitud aún no tiene decisión.
         */
        get: operations["getCreditApplicationDecision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credit-applications/{applicationId}/reevaluations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identificador de la solicitud de crédito.
                 * @example 7f3b6c1e-2a4d-4e8b-9c0f-1d2e3f4a5b6c
                 */
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-evaluar una solicitud en revisión
         * @description Decisión humana (*human-in-the-loop*) sobre una solicitud en estado `in_review`.
         *     Solo analistas de riesgo. La justificación queda en el log de auditoría.
         */
        post: operations["createReevaluation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity-verifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar verificación de identidad
         * @description Envía la cédula y la fotografía al proveedor KYC. Las imágenes no se almacenan en CrediScore.
         *     Si el proveedor no está disponible, la verificación queda en `pending` y se reintenta.
         */
        post: operations["createIdentityVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity-verifications/{verificationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identificador de la verificación de identidad.
                 * @example 0b9d2f4a-6c1e-4a7b-8d3f-5e6a7b8c9d0e
                 */
                verificationId: string;
            };
            cookie?: never;
        };
        /**
         * Obtener una verificación de identidad
         * @description Devuelve el estado de la verificación.
         */
        get: operations["getIdentityVerification"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface webhooks {
    creditApplicationDecided: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aviso de decisión tomada
         * @description CrediScore lo envía a la URL registrada por el partner cuando una solicitud queda
         *     aprobada, rechazada o en revisión. La entrega es *at-least-once*: el receptor debe
         *     ser idempotente por `event_id`.
         */
        post: operations["onCreditApplicationDecided"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface components {
    schemas: {
        /**
         * @description RUT chileno sin puntos, con guion y dígito verificador.
         * @example 12345678-5
         */
        Rut: string;
        /**
         * @description Estado de la solicitud. `received` → `fraud_check` → `scoring` → `approved`, `rejected` o
         *     `in_review`. `blocked` indica una alerta de fraude.
         * @enum {string}
         */
        ApplicationStatus: "received" | "fraud_check" | "scoring" | "approved" | "rejected" | "in_review" | "blocked";
        CreditApplicationInput: {
            rut: components["schemas"]["Rut"];
            /** @description Monto solicitado en pesos chilenos. */
            amount: number;
            /** @description Plazo en meses. */
            term_months: number;
            /**
             * Format: uuid
             * @description Verificación de identidad aprobada del solicitante.
             */
            identity_verification_id: string;
            /** @description Identificador de la operación en el sistema del partner. */
            partner_reference?: string;
        };
        CreditApplication: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["ApplicationStatus"];
            rut: components["schemas"]["Rut"];
            amount: number;
            term_months: number;
            /** Format: uuid */
            identity_verification_id: string;
            partner_reference?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreditApplicationPage: {
            data: components["schemas"]["CreditApplication"][];
            /** @description Cursor de la página siguiente; `null` si no hay más resultados. */
            next_cursor: string | null;
        };
        Decision: {
            /** Format: uuid */
            application_id: string;
            /** @enum {string} */
            outcome: "approved" | "rejected" | "review";
            /** @description Puntaje de riesgo; `null` si la solicitud se bloqueó por fraude antes del scoring. */
            score: number | null;
            /** @enum {string|null} */
            risk_band: "low" | "medium" | "medium_no_history" | "high" | null;
            /** @description Códigos de razón que explican la decisión. */
            reasons: string[];
            /** @description Versión del modelo que calculó el puntaje. */
            model_version: string | null;
            /** @enum {string} */
            decided_by: "model" | "analyst";
            /** Format: date-time */
            decided_at: string;
        };
        ReevaluationInput: {
            /** @enum {string} */
            outcome: "approved" | "rejected";
            /** @description Motivo de la decisión; se guarda en el log de auditoría. */
            justification: string;
        };
        IdentityVerificationInput: {
            rut: components["schemas"]["Rut"];
            /** @description Imagen del frente de la cédula. */
            document_image: string;
            /** @description Fotografía del solicitante. */
            selfie_image: string;
        };
        IdentityVerification: {
            /** Format: uuid */
            id: string;
            /**
             * @description `retry_required` pide capturar de nuevo un documento ilegible o vencido.
             * @enum {string}
             */
            status: "pending" | "verified" | "rejected" | "retry_required";
            rut: components["schemas"]["Rut"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            verified_at?: string | null;
        };
        CreditApplicationDecidedEvent: {
            /** Format: uuid */
            event_id: string;
            /** @enum {string} */
            event_type: "credit-application.approved" | "credit-application.rejected" | "credit-application.review-requested";
            event_version: string;
            /** Format: date-time */
            occurred_at: string;
            trace_id: string;
            data: components["schemas"]["Decision"];
        };
        /** @description Error en formato RFC 7807. */
        Problem: {
            /**
             * Format: uri
             * @description URI que identifica el tipo de error.
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri-reference */
            instance?: string;
            trace_id?: string;
        };
    };
    responses: {
        /** @description Token ausente, expirado o inválido. No se registra ninguna operación. */
        Unauthorized: {
            headers: {
                "X-Trace-Id": components["headers"]["XTraceId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description El token es válido pero no tiene permiso para esta operación. */
        Forbidden: {
            headers: {
                "X-Trace-Id": components["headers"]["XTraceId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description El recurso no existe o todavía no está disponible. */
        NotFound: {
            headers: {
                "X-Trace-Id": components["headers"]["XTraceId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description La `Idempotency-Key` ya se usó con un cuerpo distinto. */
        IdempotencyConflict: {
            headers: {
                "X-Trace-Id": components["headers"]["XTraceId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description La solicitud no está en un estado que permita la operación. */
        StateConflict: {
            headers: {
                "X-Trace-Id": components["headers"]["XTraceId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description El cuerpo no cumple el contrato o una regla de negocio. */
        ValidationError: {
            headers: {
                "X-Trace-Id": components["headers"]["XTraceId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Se superó el límite de 100 peticiones por minuto del partner. */
        RateLimited: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                "X-Trace-Id": components["headers"]["XTraceId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /**
         * @description Clave única por operación. Reintentar con la misma clave no duplica el recurso.
         * @example 9c4a1f0e-3b2d-4c5e-8f7a-6b5c4d3e2f1a
         */
        IdempotencyKey: string;
        /**
         * @description Identificador de la solicitud de crédito.
         * @example 7f3b6c1e-2a4d-4e8b-9c0f-1d2e3f4a5b6c
         */
        ApplicationId: string;
        /**
         * @description Cursor opaco devuelto en `next_cursor` por la página anterior.
         * @example eyJpZCI6IjdmM2I2YzFlIn0
         */
        Cursor: string;
        /** @description Tamaño máximo de la página. */
        Limit: number;
    };
    requestBodies: never;
    headers: {
        /** @description URL del recurso creado. */
        Location: string;
        /** @description `true` cuando la respuesta proviene de un reintento con una clave ya procesada. */
        IdempotentReplayed: boolean;
        /** @description Identificador de traza para correlacionar la petición con logs y eventos. */
        XTraceId: string;
        /** @description Peticiones restantes en la ventana actual (100 por minuto por partner). */
        XRateLimitRemaining: number;
        /** @description Segundos que hay que esperar antes de reintentar. */
        RetryAfter: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCreditApplications: {
        parameters: {
            query?: {
                /**
                 * @description Cursor opaco devuelto en `next_cursor` por la página anterior.
                 * @example eyJpZCI6IjdmM2I2YzFlIn0
                 */
                cursor?: components["parameters"]["Cursor"];
                /** @description Tamaño máximo de la página. */
                limit?: components["parameters"]["Limit"];
                /** @description Filtra por estado de la solicitud. */
                status?: components["schemas"]["ApplicationStatus"];
                /**
                 * @description Solo solicitudes creadas en esta fecha y hora o después.
                 * @example 2026-10-01T00:00:00Z
                 */
                "created_at.gte"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de solicitudes. */
            200: {
                headers: {
                    "X-Trace-Id": components["headers"]["XTraceId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditApplicationPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    createCreditApplication: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Clave única por operación. Reintentar con la misma clave no duplica el recurso.
                 * @example 9c4a1f0e-3b2d-4c5e-8f7a-6b5c4d3e2f1a
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreditApplicationInput"];
            };
        };
        responses: {
            /** @description Solicitud creada, o respuesta original de un reintento idempotente. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    "X-Trace-Id": components["headers"]["XTraceId"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditApplication"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    getCreditApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identificador de la solicitud de crédito.
                 * @example 7f3b6c1e-2a4d-4e8b-9c0f-1d2e3f4a5b6c
                 */
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Solicitud encontrada. */
            200: {
                headers: {
                    "X-Trace-Id": components["headers"]["XTraceId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditApplication"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getCreditApplicationDecision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identificador de la solicitud de crédito.
                 * @example 7f3b6c1e-2a4d-4e8b-9c0f-1d2e3f4a5b6c
                 */
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Decisión disponible. */
            200: {
                headers: {
                    "X-Trace-Id": components["headers"]["XTraceId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Decision"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createReevaluation: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Clave única por operación. Reintentar con la misma clave no duplica el recurso.
                 * @example 9c4a1f0e-3b2d-4c5e-8f7a-6b5c4d3e2f1a
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /**
                 * @description Identificador de la solicitud de crédito.
                 * @example 7f3b6c1e-2a4d-4e8b-9c0f-1d2e3f4a5b6c
                 */
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReevaluationInput"];
            };
        };
        responses: {
            /** @description Re-evaluación registrada; devuelve la nueva decisión. */
            201: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    "X-Trace-Id": components["headers"]["XTraceId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Decision"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["StateConflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    createIdentityVerification: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Clave única por operación. Reintentar con la misma clave no duplica el recurso.
                 * @example 9c4a1f0e-3b2d-4c5e-8f7a-6b5c4d3e2f1a
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentityVerificationInput"];
            };
        };
        responses: {
            /** @description Verificación creada. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    "Idempotent-Replayed": components["headers"]["IdempotentReplayed"];
                    "X-Trace-Id": components["headers"]["XTraceId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityVerification"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    getIdentityVerification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identificador de la verificación de identidad.
                 * @example 0b9d2f4a-6c1e-4a7b-8d3f-5e6a7b8c9d0e
                 */
                verificationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verificación encontrada. */
            200: {
                headers: {
                    "X-Trace-Id": components["headers"]["XTraceId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityVerification"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    onCreditApplicationDecided: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreditApplicationDecidedEvent"];
            };
        };
        responses: {
            /** @description Aviso recibido. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
